# Generated by Django 5.2.10 on 2026-01-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_compra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.promocion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
